name: init

inputs:
  GO_VERSION:
    description: "Go Version"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.GO_VERSION }}

    - name: Download Go Modules
      run: go mod download
      shell: sh
